### PR TITLE
Small fixes for non-root url location

### PR DESCRIPTION
**Pull request by KickerTom**
As described in issue #236, I had problems when the root path of the url was not empty (etherdraw not running on dedicated address). These changes seems to fix that. Also added a fix for non-working background toggle button.

### CODE REVIEW

**Comment by JohnMcLear** [comment]
Good spot and good fixes!  Thanks :)

**Comment by rugk** [comment]
Ah same issues I also had to fix, https://github.com/JohnMcLear/ep_markdown/pull/17... :smiley: 

@JohnMcLear Next time you should really make sure to use the relative paths...

**Comment by rugk** [comment]
Can this patch please also be included in the master branch?

As a fix this is quite useful...

**Comment by rugk** [comment]
So I "ported" the PR, see other PR.

**Comment by JohnMcLear** [comment]
Open a pull request

On 11 May 2016 9:51 p.m., rugk <notifications@github.com> wrote:

Can this patch please also be included in the master branch?

As a fix this is quite useful...

**Comment by rugk** [comment]
Already did. :smile:

**Comment by JohnMcLear** [comment]
Nice thanks done

On 11 May 2016 10:40 p.m., rugk <notifications@github.com> wrote:

Already did. [:smile:]

**Pull request merged**
