### PR TITLE
Canvas Panning!

### PR DESCRIPTION
**Pull request by theelectricwiz**
Got panning working for middle click and 2 finger gestures. There is a little bug where it is possible that artifacts are drawn at the start/end of the 2 finger gesture. Not sure best how to fix this though...

### CODE REVIEW

**Comment by theelectricwiz** [comment]
Have just noticed a bug (Firefox 38.4 on Linux) where the mouse drag events don't have the correct button in them, so you can't pan in firefox. Will investigate.

**Comment by theelectricwiz** [comment]
Will close and redo as have added shift+click panning

**Comment by JohnMcLear** [comment]
be mindful of tablet etc. users who don't have shift.

**Comment by theelectricwiz** [comment]
Indeed. They can still use the two finger gesture.

**Pull request closed without merging**
