### PR TITLE
Canvas Panning AND Scaling

### PR DESCRIPTION
**Pull request by theelectricwiz**
Implemented canvas panning and scaling.
With mouse:
- can pan holding down middle button, or SHIFT + left button
- can scale with wheel.
With 2 fingers:
- can pan by moving fingers around
- can scale by pinching

Added a zero button to take the canvas back to 0,0, so have a easy way of getting back to the start
Added a coordinates status box so can keep track of where you are in the canvas and what the zoom factor is

### CODE REVIEW

**Comment by JohnMcLear** [comment]
Probably difficult to do but can you also add some tests please? :)

**Comment by theelectricwiz** [comment]
Should be able to. Will have a think / look. Cheers.

**Comment by theelectricwiz** [comment]
Hmm. jquer.simulate.js doesn't have the capability needed for testing these events (middle click and touch events). Don't suppose you know of any libraries that do?

**Comment by theoryshaw** [comment]
> Added a zero button to take the canvas back to 0,0, so have a easy way of getting back to the start

Another user pattern you see quick a bit with various architect/eng tools, is double clicking with the middle mouse button(or wheel) and it zooms to the extents of the contents.

**Pull request merged**
